# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Accessibility of the Location
  class Accessibility < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Accessibility Status
    # @return [AccessibilityStatusEnum]
    attr_accessor :status

    # optional Arbitrary text about restrictions of the Location
    # @return [String]
    attr_accessor :remark

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash['remark'] = 'remark'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        status
        remark
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(status = SKIP, remark = SKIP)
      @status = status unless status == SKIP
      @remark = remark unless remark == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash.key?('status') ? hash['status'] : SKIP
      remark = hash.key?('remark') ? hash['remark'] : SKIP

      # Create object from extracted values.
      Accessibility.new(status,
                        remark)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} status: #{@status}, remark: #{@remark}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} status: #{@status.inspect}, remark: #{@remark.inspect}>"
    end
  end
end
