# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Accessibility Status
  class AccessibilityStatusEnum
    ACCESSIBILITY_STATUS_ENUM = [
      # TODO: Write general description for FREEPUBLIC
      FREEPUBLIC = 'FreePublic'.freeze,

      # TODO: Write general description for PAYINGPUBLIC
      PAYINGPUBLIC = 'PayingPublic'.freeze,

      # TODO: Write general description for RESTRICTED
      RESTRICTED = 'Restricted'.freeze,

      # TODO: Write general description for UNSPECIFIED
      UNSPECIFIED = 'Unspecified'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ACCESSIBILITY_STATUS_ENUM.include?(value)
    end
  end
end
