# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Accessibility Status
  class AccessibilityStatusEnum
    ACCESSIBILITY_STATUS_ENUM = [
      # TODO: Write general description for FREEPUBLIC
      FREEPUBLIC = 'FreePublic'.freeze,

      # TODO: Write general description for PAYINGPUBLIC
      PAYINGPUBLIC = 'PayingPublic'.freeze,

      # TODO: Write general description for RESTRICTED
      RESTRICTED = 'Restricted'.freeze,

      # TODO: Write general description for UNSPECIFIED
      UNSPECIFIED = 'Unspecified'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ACCESSIBILITY_STATUS_ENUM.include?(value)
    end

    def self.from_value(value, default_value = FREEPUBLIC)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'freepublic' then FREEPUBLIC
      when 'payingpublic' then PAYINGPUBLIC
      when 'restricted' then RESTRICTED
      when 'unspecified' then UNSPECIFIED
      else
        default_value
      end
    end
  end
end
