# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Accessibility of the Location
  class AccessibilityV2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Accessibility Status
    # @return [AccessibilityStatusEnum]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(status = SKIP)
      @status = status unless status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash.key?('status') ? hash['status'] : SKIP

      # Create object from extracted values.
      AccessibilityV2.new(status)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} status: #{@status}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} status: #{@status.inspect}>"
    end
  end
end
