# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Indicates overall status of the request
  class ActiveResponse200JsonStatusEnum
    ACTIVE_RESPONSE200_JSON_STATUS_ENUM = [
      # TODO: Write general description for SUCCESS
      SUCCESS = 'SUCCESS'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ACTIVE_RESPONSE200_JSON_STATUS_ENUM.include?(value)
    end
  end
end
