# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # ChargesessionStartBody Model.
  class ChargesessionStartBody < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The EV Charge Number which can be found on the back of the Shell EV Card
    # @return [String]
    attr_accessor :ev_charge_number

    # Standard EVSE (Electric Vehicle Supply Equipment) Id identifier
    # (ISO-IEC-15118)
    # @return [String]
    attr_accessor :evse_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ev_charge_number'] = 'EvChargeNumber'
      @_hash['evse_id'] = 'EvseId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(ev_charge_number = nil,
                   evse_id = nil)
      @ev_charge_number = ev_charge_number
      @evse_id = evse_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ev_charge_number =
        hash.key?('EvChargeNumber') ? hash['EvChargeNumber'] : nil
      evse_id = hash.key?('EvseId') ? hash['EvseId'] : nil

      # Create object from extracted values.
      ChargesessionStartBody.new(ev_charge_number,
                                 evse_id)
    end
  end
end
