# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # An EVSE can have one or many Connectors. Each Connector will normally have a
  # different socket / cable and only one can be used to charge at a time.
  class ConnectorV2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Internal identifier used to refer to this Connector
    # @return [String]
    attr_accessor :uid

    # Identifier of the Evse as given by the Operator, unique for the containing
    # EVSE'
    # @return [String]
    attr_accessor :external_id

    # Type of the connector in the EVSE unit.
    # @return [ConnectorVOConnectorTypeEnum]
    attr_accessor :connector_type

    # Electrical Properties of the Connector
    # @return [ElectricalPropertiesV2]
    attr_accessor :electrical_properties

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['uid'] = 'uid'
      @_hash['external_id'] = 'externalId'
      @_hash['connector_type'] = 'connectorType'
      @_hash['electrical_properties'] = 'electricalProperties'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        uid
        external_id
        connector_type
        electrical_properties
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(uid = SKIP, external_id = SKIP, connector_type = SKIP,
                   electrical_properties = SKIP)
      @uid = uid unless uid == SKIP
      @external_id = external_id unless external_id == SKIP
      @connector_type = connector_type unless connector_type == SKIP
      @electrical_properties = electrical_properties unless electrical_properties == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      uid = hash.key?('uid') ? hash['uid'] : SKIP
      external_id = hash.key?('externalId') ? hash['externalId'] : SKIP
      connector_type = hash.key?('connectorType') ? hash['connectorType'] : SKIP
      electrical_properties = ElectricalPropertiesV2.from_hash(hash['electricalProperties']) if
        hash['electricalProperties']

      # Create object from extracted values.
      ConnectorV2.new(uid,
                      external_id,
                      connector_type,
                      electrical_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} uid: #{@uid}, external_id: #{@external_id}, connector_type:"\
      " #{@connector_type}, electrical_properties: #{@electrical_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} uid: #{@uid.inspect}, external_id: #{@external_id.inspect}, connector_type:"\
      " #{@connector_type.inspect}, electrical_properties: #{@electrical_properties.inspect}>"
    end
  end
end
