# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Source of the last update
  class ConnectorVOUpdatedByEnum
    CONNECTOR_VO_UPDATED_BY_ENUM = [
      # TODO: Write general description for FEED
      FEED = 'Feed'.freeze,

      # TODO: Write general description for ADMIN
      ADMIN = 'Admin'.freeze,

      # TODO: Write general description for TARIFFSERVICE
      TARIFFSERVICE = 'TariffService'.freeze,

      # TODO: Write general description for DEFAULTS
      DEFAULTS = 'Defaults'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CONNECTOR_VO_UPDATED_BY_ENUM.include?(value)
    end

    def self.from_value(value, default_value = FEED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'feed' then FEED
      when 'admin' then ADMIN
      when 'tariffservice' then TARIFFSERVICE
      when 'defaults' then DEFAULTS
      else
        default_value
      end
    end
  end
end
