# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module ShellEv
  # DataActive Model.
  class DataActive < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Id of the session
    # @return [UUID | String]
    attr_accessor :id

    # Id of the user that started the session
    # @return [String]
    attr_accessor :user_id

    # Id of the evse that the user is charging
    # @return [String]
    attr_accessor :ema_id

    # Electric Vehicle Supply Equipment Identifier. An EVSEID identifies a
    # Charging Point.
    # @return [String]
    attr_accessor :evse_id

    # When the session is started
    # @return [DateTime]
    attr_accessor :started_at

    # When the session is stopped
    # @return [DateTime]
    attr_accessor :stopped_at

    # When the session is stopped
    # @return [ChargeRetrieveState]
    attr_accessor :session_state

    # When the session is stopped
    # @return [String]
    attr_accessor :last_updated

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['user_id'] = 'userId'
      @_hash['ema_id'] = 'emaId'
      @_hash['evse_id'] = 'evseId'
      @_hash['started_at'] = 'startedAt'
      @_hash['stopped_at'] = 'stoppedAt'
      @_hash['session_state'] = 'SessionState'
      @_hash['last_updated'] = 'lastUpdated'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        user_id
        ema_id
        evse_id
        started_at
        stopped_at
        session_state
        last_updated
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        stopped_at
      ]
    end

    def initialize(id = SKIP, user_id = SKIP, ema_id = SKIP, evse_id = SKIP,
                   started_at = SKIP, stopped_at = SKIP, session_state = SKIP,
                   last_updated = SKIP)
      @id = id unless id == SKIP
      @user_id = user_id unless user_id == SKIP
      @ema_id = ema_id unless ema_id == SKIP
      @evse_id = evse_id unless evse_id == SKIP
      @started_at = started_at unless started_at == SKIP
      @stopped_at = stopped_at unless stopped_at == SKIP
      @session_state = session_state unless session_state == SKIP
      @last_updated = last_updated unless last_updated == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      user_id = hash.key?('userId') ? hash['userId'] : SKIP
      ema_id = hash.key?('emaId') ? hash['emaId'] : SKIP
      evse_id = hash.key?('evseId') ? hash['evseId'] : SKIP
      started_at = if hash.key?('startedAt')
                     (DateTimeHelper.from_rfc3339(hash['startedAt']) if hash['startedAt'])
                   else
                     SKIP
                   end
      stopped_at = if hash.key?('stoppedAt')
                     (DateTimeHelper.from_rfc3339(hash['stoppedAt']) if hash['stoppedAt'])
                   else
                     SKIP
                   end
      session_state = ChargeRetrieveState.from_hash(hash['SessionState']) if hash['SessionState']
      last_updated = hash.key?('lastUpdated') ? hash['lastUpdated'] : SKIP

      # Create object from extracted values.
      DataActive.new(id,
                     user_id,
                     ema_id,
                     evse_id,
                     started_at,
                     stopped_at,
                     session_state,
                     last_updated)
    end

    def to_custom_started_at
      DateTimeHelper.to_rfc3339(started_at)
    end

    def to_custom_stopped_at
      DateTimeHelper.to_rfc3339(stopped_at)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, user_id: #{@user_id}, ema_id: #{@ema_id}, evse_id: #{@evse_id},"\
      " started_at: #{@started_at}, stopped_at: #{@stopped_at}, session_state: #{@session_state},"\
      " last_updated: #{@last_updated}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, user_id: #{@user_id.inspect}, ema_id:"\
      " #{@ema_id.inspect}, evse_id: #{@evse_id.inspect}, started_at: #{@started_at.inspect},"\
      " stopped_at: #{@stopped_at.inspect}, session_state: #{@session_state.inspect},"\
      " last_updated: #{@last_updated.inspect}>"
    end
  end
end
