# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Describes the session state
  class DataActiveSessionStateEnum
    DATA_ACTIVE_SESSION_STATE_ENUM = [
      # TODO: Write general description for STARTED
      STARTED = 'started'.freeze,

      # TODO: Write general description for STOPPED
      STOPPED = 'stopped'.freeze,

      # TODO: Write general description for STARTREQUESTED
      STARTREQUESTED = 'start-requested'.freeze,

      # TODO: Write general description for STOPREQUESTED
      STOPREQUESTED = 'stop-requested'.freeze,

      # TODO: Write general description for FAILEDTOSTART
      FAILEDTOSTART = 'failed-to-start'.freeze,

      # TODO: Write general description for FAILEDTOSTOP
      FAILEDTOSTOP = 'failed-to-stop'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      DATA_ACTIVE_SESSION_STATE_ENUM.include?(value)
    end
  end
end
