# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # DayOfWeek.
  class DayOfWeekEnum
    DAY_OF_WEEK_ENUM = [
      # TODO: Write general description for MONDAY
      MONDAY = 'MONDAY'.freeze,

      # TODO: Write general description for TUESDAY
      TUESDAY = 'TUESDAY'.freeze,

      # TODO: Write general description for WEDNESDAY
      WEDNESDAY = 'WEDNESDAY'.freeze,

      # TODO: Write general description for THURSDAY
      THURSDAY = 'THURSDAY'.freeze,

      # TODO: Write general description for FRIDAY
      FRIDAY = 'FRIDAY'.freeze,

      # TODO: Write general description for SATURDAY
      SATURDAY = 'SATURDAY'.freeze,

      # TODO: Write general description for SUNDAY
      SUNDAY = 'SUNDAY'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      DAY_OF_WEEK_ENUM.include?(value)
    end

    def self.from_value(value, default_value = MONDAY)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'monday' then MONDAY
      when 'tuesday' then TUESDAY
      when 'wednesday' then WEDNESDAY
      when 'thursday' then THURSDAY
      when 'friday' then FRIDAY
      when 'saturday' then SATURDAY
      when 'sunday' then SUNDAY
      else
        default_value
      end
    end
  end
end
