# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Power Type used in this connector.
  class ElectricalPropertiesPowerTypeEnum
    ELECTRICAL_PROPERTIES_POWER_TYPE_ENUM = [
      # TODO: Write general description for AC1PHASE
      AC1PHASE = 'AC1Phase'.freeze,

      # TODO: Write general description for AC3PHASE
      AC3PHASE = 'AC3Phase'.freeze,

      # TODO: Write general description for DC
      DC = 'DC'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ELECTRICAL_PROPERTIES_POWER_TYPE_ENUM.include?(value)
    end

    def self.from_value(value, default_value = AC1PHASE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'ac1phase' then AC1PHASE
      when 'ac3phase' then AC3PHASE
      when 'dc' then DC
      else
        default_value
      end
    end
  end
end
