# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Power Type used in this connector.
  class ElectricalPropertiesPowerTypeEnum
    ELECTRICAL_PROPERTIES_POWER_TYPE_ENUM = [
      # TODO: Write general description for AC1PHASE
      AC1PHASE = 'AC1Phase'.freeze,

      # TODO: Write general description for AC3PHASE
      AC3PHASE = 'AC3Phase'.freeze,

      # TODO: Write general description for DC
      DC = 'DC'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ELECTRICAL_PROPERTIES_POWER_TYPE_ENUM.include?(value)
    end
  end
end
