# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # env.
  class EnvEnum
    ENV_ENUM = [
      # TODO: Write general description for ENUM_APITESTSHELLCOM
      ENUM_APITESTSHELLCOM = 'api-test.shell.com'.freeze,

      # TODO: Write general description for ENUM_APISHELLCOM
      ENUM_APISHELLCOM = 'api.shell.com'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ENV_ENUM.include?(value)
    end
  end
end
