# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # The current status of the EVSE units availability
  class EvseVOStatusEnum
    EVSE_VO_STATUS_ENUM = [
      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'Available'.freeze,

      # TODO: Write general description for OCCUPIED
      OCCUPIED = 'Occupied'.freeze,

      # TODO: Write general description for UNAVAILABLE
      UNAVAILABLE = 'Unavailable'.freeze,

      # TODO: Write general description for UNKNOWN
      UNKNOWN = 'Unknown'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EVSE_VO_STATUS_ENUM.include?(value)
    end

    def self.from_value(value, default_value = AVAILABLE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'available' then AVAILABLE
      when 'occupied' then OCCUPIED
      when 'unavailable' then UNAVAILABLE
      when 'unknown' then UNKNOWN
      else
        default_value
      end
    end
  end
end
