# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Filter by Locations that support the given Authorization Methods
  class GetEVLocationsAuthorizationMethodsEnum
    GET_EV_LOCATIONS_AUTHORIZATION_METHODS_ENUM = [
      # TODO: Write general description for NEWMOTIONAPP
      NEWMOTIONAPP = 'NewMotionApp'.freeze,

      # TODO: Write general description for RFIDTOKEN
      RFIDTOKEN = 'RFIDToken'.freeze,

      # TODO: Write general description for PNC
      PNC = 'PnC'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      GET_EV_LOCATIONS_AUTHORIZATION_METHODS_ENUM.include?(value)
    end

    def self.from_value(value, default_value = NEWMOTIONAPP)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'newmotionapp' then NEWMOTIONAPP
      when 'rfidtoken' then RFIDTOKEN
      when 'pnc' then PNC
      else
        default_value
      end
    end
  end
end
