# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Indicates overall status of the request
  class GetChargeSessionRetrieveResponse200JsonStatusEnum
    GET_CHARGE_SESSION_RETRIEVE_RESPONSE200_JSON_STATUS_ENUM = [
      # TODO: Write general description for SUCCESS
      SUCCESS = 'SUCCESS'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      GET_CHARGE_SESSION_RETRIEVE_RESPONSE200_JSON_STATUS_ENUM.include?(value)
    end

    def self.from_value(value, default_value = SUCCESS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'success' then SUCCESS
      when 'failed' then FAILED
      else
        default_value
      end
    end
  end
end
