# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Filter by Locations that have Connectors with the set of Connector Types
  class GetEVLocationsConnectorTypesEnum
    GET_EV_LOCATIONS_CONNECTOR_TYPES_ENUM = [
      # TODO: Write general description for AVCON
      AVCON = 'Avcon'.freeze,

      # TODO: Write general description for DOMESTIC
      DOMESTIC = 'Domestic'.freeze,

      # TODO: Write general description for INDUSTRIAL2PDC
      INDUSTRIAL2PDC = 'Industrial2PDc'.freeze,

      # TODO: Write general description for INDUSTRIALPNEAC
      INDUSTRIALPNEAC = 'IndustrialPneAc'.freeze,

      # TODO: Write general description for INDUSTRIAL3PEAC
      INDUSTRIAL3PEAC = 'Industrial3PEAc'.freeze,

      # TODO: Write general description for INDUSTRIAL3PENAC
      INDUSTRIAL3PENAC = 'Industrial3PENAc'.freeze,

      # TODO: Write general description for TYPE1
      TYPE1 = 'Type1'.freeze,

      # TODO: Write general description for TYPE1COMBO
      TYPE1COMBO = 'Type1Combo'.freeze,

      # TODO: Write general description for TYPE2
      TYPE2 = 'Type2'.freeze,

      # TODO: Write general description for TYPE2COMBO
      TYPE2COMBO = 'Type2Combo'.freeze,

      # TODO: Write general description for TYPE3
      TYPE3 = 'Type3'.freeze,

      # TODO: Write general description for LPI
      LPI = 'LPI'.freeze,

      # TODO: Write general description for NEMA520
      NEMA520 = 'Nema520'.freeze,

      # TODO: Write general description for SAEJ1772
      SAEJ1772 = 'SAEJ1772'.freeze,

      # TODO: Write general description for SPI
      SPI = 'SPI'.freeze,

      # TODO: Write general description for TEPCOCHADEMO
      TEPCOCHADEMO = 'TepcoCHAdeMO'.freeze,

      # TODO: Write general description for TESLA
      TESLA = 'Tesla'.freeze,

      # TODO: Write general description for UNSPECIFIED
      UNSPECIFIED = 'Unspecified'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      GET_EV_LOCATIONS_CONNECTOR_TYPES_ENUM.include?(value)
    end

    def self.from_value(value, default_value = AVCON)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'avcon' then AVCON
      when 'domestic' then DOMESTIC
      when 'industrial2pdc' then INDUSTRIAL2PDC
      when 'industrialpneac' then INDUSTRIALPNEAC
      when 'industrial3peac' then INDUSTRIAL3PEAC
      when 'industrial3penac' then INDUSTRIAL3PENAC
      when 'type1' then TYPE1
      when 'type1combo' then TYPE1COMBO
      when 'type2' then TYPE2
      when 'type2combo' then TYPE2COMBO
      when 'type3' then TYPE3
      when 'lpi' then LPI
      when 'nema520' then NEMA520
      when 'saej1772' then SAEJ1772
      when 'spi' then SPI
      when 'tepcochademo' then TEPCOCHADEMO
      when 'tesla' then TESLA
      when 'unspecified' then UNSPECIFIED
      else
        default_value
      end
    end
  end
end
