# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # GetMarkersListConnectorTypes.
  class GetMarkersListConnectorTypesEnum
    GET_MARKERS_LIST_CONNECTOR_TYPES_ENUM = [
      # TODO: Write general description for AVCON
      AVCON = 'Avcon'.freeze,

      # TODO: Write general description for DOMESTIC
      DOMESTIC = 'Domestic'.freeze,

      # TODO: Write general description for INDUSTRIAL2PDC
      INDUSTRIAL2PDC = 'Industrial2PDc'.freeze,

      # TODO: Write general description for INDUSTRIALPNEAC
      INDUSTRIALPNEAC = 'IndustrialPneAc'.freeze,

      # TODO: Write general description for INDUSTRIAL3PEAC
      INDUSTRIAL3PEAC = 'Industrial3PEAc'.freeze,

      # TODO: Write general description for INDUSTRIAL3PENAC
      INDUSTRIAL3PENAC = 'Industrial3PENAc'.freeze,

      # TODO: Write general description for TYPE1
      TYPE1 = 'Type1'.freeze,

      # TODO: Write general description for TYPE1COMBO
      TYPE1COMBO = 'Type1Combo'.freeze,

      # TODO: Write general description for TYPE2
      TYPE2 = 'Type2'.freeze,

      # TODO: Write general description for TYPE2COMBO
      TYPE2COMBO = 'Type2Combo'.freeze,

      # TODO: Write general description for TYPE3
      TYPE3 = 'Type3'.freeze,

      # TODO: Write general description for LPI
      LPI = 'LPI'.freeze,

      # TODO: Write general description for NEMA520
      NEMA520 = 'Nema520'.freeze,

      # TODO: Write general description for SAEJ1772
      SAEJ1772 = 'SAEJ1772'.freeze,

      # TODO: Write general description for SPI
      SPI = 'SPI'.freeze,

      # TODO: Write general description for TEPCOCHADEMO
      TEPCOCHADEMO = 'TepcoCHAdeMO'.freeze,

      # TODO: Write general description for TESLA
      TESLA = 'Tesla'.freeze,

      # TODO: Write general description for UNSPECIFIED
      UNSPECIFIED = 'Unspecified'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      GET_MARKERS_LIST_CONNECTOR_TYPES_ENUM.include?(value)
    end
  end
end
