# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Filter by Locations that have the given status
  class GetEVLocationsEvseStatusEnum
    GET_EV_LOCATIONS_EVSE_STATUS_ENUM = [
      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'Available'.freeze,

      # TODO: Write general description for OCCUPIED
      OCCUPIED = 'Occupied'.freeze,

      # TODO: Write general description for UNAVAILABLE
      UNAVAILABLE = 'Unavailable'.freeze,

      # TODO: Write general description for UNKNOWN
      UNKNOWN = 'Unknown'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      GET_EV_LOCATIONS_EVSE_STATUS_ENUM.include?(value)
    end
  end
end
