# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # InlineResponse202Data Model.
  class InlineResponse202Data < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Session Id for tracking.
    # @return [String]
    attr_accessor :session_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['session_id'] = 'sessionId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        session_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(session_id = SKIP)
      @session_id = session_id unless session_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      session_id = hash.key?('sessionId') ? hash['sessionId'] : SKIP

      # Create object from extracted values.
      InlineResponse202Data.new(session_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} session_id: #{@session_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} session_id: #{@session_id.inspect}>"
    end
  end
end
