# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # A Marker is a place on the map that represent multiple Locations at the same
  # spot
  class MultiLocationMarkerV2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Coordinates of the Shell Recharge Site Location
    # @return [Coordinates]
    attr_accessor :coordinates

    # Number of Locations that this Marker represents in the given set of bounds
    # @return [Float]
    attr_accessor :location_count

    # Total number of Evses in Locations that this Marker represents
    # @return [Float]
    attr_accessor :evse_count

    # Maximum power in kW across all locations grouped in this marker
    # (disregarding availability)
    # @return [Float]
    attr_accessor :max_power

    # Operator of this Shell Recharge Location
    # @return [String]
    attr_accessor :operator_name

    # Type of the Marker, in this case it will always be MultiLocation
    # @return [String]
    attr_reader :marker_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['coordinates'] = 'coordinates'
      @_hash['location_count'] = 'locationCount'
      @_hash['evse_count'] = 'evseCount'
      @_hash['max_power'] = 'maxPower'
      @_hash['operator_name'] = 'operatorName'
      @_hash['marker_type'] = 'markerType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        coordinates
        location_count
        evse_count
        max_power
        operator_name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(coordinates = SKIP, location_count = SKIP, evse_count = SKIP,
                   max_power = SKIP, operator_name = SKIP)
      @coordinates = coordinates unless coordinates == SKIP
      @location_count = location_count unless location_count == SKIP
      @evse_count = evse_count unless evse_count == SKIP
      @max_power = max_power unless max_power == SKIP
      @operator_name = operator_name unless operator_name == SKIP
      @marker_type = 'MultiLocation'
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      coordinates = Coordinates.from_hash(hash['coordinates']) if hash['coordinates']
      location_count = hash.key?('locationCount') ? hash['locationCount'] : SKIP
      evse_count = hash.key?('evseCount') ? hash['evseCount'] : SKIP
      max_power = hash.key?('maxPower') ? hash['maxPower'] : SKIP
      operator_name = hash.key?('operatorName') ? hash['operatorName'] : SKIP

      # Create object from extracted values.
      MultiLocationMarkerV2.new(coordinates,
                                location_count,
                                evse_count,
                                max_power,
                                operator_name)
    end

    # Validates an instance of the object from a given value.
    # @param [MultiLocationMarkerV2 | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.marker_type,
                                     ->(val) { val.instance_of? String })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['markerType'],
                            ->(val) { val.instance_of? String })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} coordinates: #{@coordinates}, location_count: #{@location_count},"\
      " evse_count: #{@evse_count}, max_power: #{@max_power}, operator_name: #{@operator_name},"\
      " marker_type: #{@marker_type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} coordinates: #{@coordinates.inspect}, location_count:"\
      " #{@location_count.inspect}, evse_count: #{@evse_count.inspect}, max_power:"\
      " #{@max_power.inspect}, operator_name: #{@operator_name.inspect}, marker_type:"\
      " #{@marker_type.inspect}>"
    end
  end
end
