# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # 3 letter day of the week
  class OpeningHoursObjectWeekDayEnum
    OPENING_HOURS_OBJECT_WEEK_DAY_ENUM = [
      # TODO: Write general description for SUN
      SUN = 'Sun'.freeze,

      # TODO: Write general description for MON
      MON = 'Mon'.freeze,

      # TODO: Write general description for TUE
      TUE = 'Tue'.freeze,

      # TODO: Write general description for WED
      WED = 'Wed'.freeze,

      # TODO: Write general description for THU
      THU = 'Thu'.freeze,

      # TODO: Write general description for FRI
      FRI = 'Fri'.freeze,

      # TODO: Write general description for SAT
      SAT = 'Sat'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OPENING_HOURS_OBJECT_WEEK_DAY_ENUM.include?(value)
    end

    def self.from_value(value, default_value = SUN)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'sun' then SUN
      when 'mon' then MON
      when 'tue' then TUE
      when 'wed' then WED
      when 'thu' then THU
      when 'fri' then FRI
      when 'sat' then SAT
      else
        default_value
      end
    end
  end
end
