# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # 3 letter day of the week
  class OpeningHoursObjectWeekDayEnum
    OPENING_HOURS_OBJECT_WEEK_DAY_ENUM = [
      # TODO: Write general description for SUN
      SUN = 'Sun'.freeze,

      # TODO: Write general description for MON
      MON = 'Mon'.freeze,

      # TODO: Write general description for TUE
      TUE = 'Tue'.freeze,

      # TODO: Write general description for WED
      WED = 'Wed'.freeze,

      # TODO: Write general description for THU
      THU = 'Thu'.freeze,

      # TODO: Write general description for FRI
      FRI = 'Fri'.freeze,

      # TODO: Write general description for SAT
      SAT = 'Sat'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OPENING_HOURS_OBJECT_WEEK_DAY_ENUM.include?(value)
    end
  end
end
