# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # OpeningHoursObject Model.
  class OpeningHoursObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [OpeningHoursObjectWeekDayEnum]
    attr_accessor :week_day

    # Hour in 24h local time when the location opens.
    # @return [String]
    attr_accessor :start_time

    # Hour in 24h local time when the location closes.
    # @return [String]
    attr_accessor :end_time

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['week_day'] = 'weekDay'
      @_hash['start_time'] = 'startTime'
      @_hash['end_time'] = 'endTime'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        week_day
        start_time
        end_time
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(week_day = SKIP, start_time = SKIP, end_time = SKIP)
      @week_day = week_day unless week_day == SKIP
      @start_time = start_time unless start_time == SKIP
      @end_time = end_time unless end_time == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      week_day = hash.key?('weekDay') ? hash['weekDay'] : SKIP
      start_time = hash.key?('startTime') ? hash['startTime'] : SKIP
      end_time = hash.key?('endTime') ? hash['endTime'] : SKIP

      # Create object from extracted values.
      OpeningHoursObject.new(week_day,
                             start_time,
                             end_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} week_day: #{@week_day}, start_time: #{@start_time}, end_time:"\
      " #{@end_time}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} week_day: #{@week_day.inspect}, start_time: #{@start_time.inspect},"\
      " end_time: #{@end_time.inspect}>"
    end
  end
end
