# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # PowerRange Model.
  class PowerRange < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Minimum supported power in kW
    # @return [Integer]
    attr_accessor :min

    # Maximum supported power in kW
    # @return [Integer]
    attr_accessor :max

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['min'] = 'min'
      @_hash['max'] = 'max'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(min = nil, max = nil)
      @min = min
      @max = max
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      min = hash.key?('min') ? hash['min'] : nil
      max = hash.key?('max') ? hash['max'] : nil

      # Create object from extracted values.
      PowerRange.new(min,
                     max)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} min: #{@min}, max: #{@max}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} min: #{@min.inspect}, max: #{@max.inspect}>"
    end
  end
end
