# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # PriceComponent Model.
  class PriceComponent < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Type of the price component
    # @return [TypeEnum]
    attr_accessor :type

    # Step size in seconds for TIME-based components, in kWh for ENERGY-based
    # components, or 1 for FLAT components
    # @return [Integer]
    attr_accessor :step_size

    # Price per step in the specified currency for this price component
    # @return [Float]
    attr_accessor :price

    # VAT percentage applicable to this price component
    # @return [Float]
    attr_accessor :vat

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['step_size'] = 'stepSize'
      @_hash['price'] = 'price'
      @_hash['vat'] = 'vat'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type = nil, step_size = nil, price = nil, vat = nil)
      @type = type
      @step_size = step_size
      @price = price
      @vat = vat
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : nil
      step_size = hash.key?('stepSize') ? hash['stepSize'] : nil
      price = hash.key?('price') ? hash['price'] : nil
      vat = hash.key?('vat') ? hash['vat'] : nil

      # Create object from extracted values.
      PriceComponent.new(type,
                         step_size,
                         price,
                         vat)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, step_size: #{@step_size}, price: #{@price}, vat: #{@vat}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, step_size: #{@step_size.inspect}, price:"\
      " #{@price.inspect}, vat: #{@vat.inspect}>"
    end
  end
end
