# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # ResponseError401AllOf1 Model.
  class ResponseError401AllOf1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Details of error(s) encountered
    # @return [Array[ResponseError401AllOf1ErrorsItems]]
    attr_accessor :errors

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['errors'] = 'Errors'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(errors = nil)
      @errors = errors
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      errors = nil
      unless hash['Errors'].nil?
        errors = []
        hash['Errors'].each do |structure|
          errors << (ResponseError401AllOf1ErrorsItems.from_hash(structure) if structure)
        end
      end

      errors = nil unless hash.key?('Errors')

      # Create object from extracted values.
      ResponseError401AllOf1.new(errors)
    end
  end
end
