# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Indicates overall status of the request
  class ResponseBaseStatusEnum
    RESPONSE_BASE_STATUS_ENUM = [
      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze,

      # TODO: Write general description for PARTIAL_SUCCESS
      PARTIAL_SUCCESS = 'PARTIAL_SUCCESS'.freeze,

      # TODO: Write general description for SUCCESS
      SUCCESS = 'SUCCESS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      RESPONSE_BASE_STATUS_ENUM.include?(value)
    end
  end
end
