# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Restrictions Model.
  class Restrictions < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Valid from this time of the day (HH:mm)
    # @return [String]
    attr_accessor :start_time

    # Valid until this time of the day (HH:mm)
    # @return [String]
    attr_accessor :end_time

    # Valid until this time of the day (HH:mm)
    # @return [Date]
    attr_accessor :start_date

    # Valid until this time of the day (HH:mm)
    # @return [Date]
    attr_accessor :end_date

    # Valid until this time of the day (HH:mm)
    # @return [Float]
    attr_accessor :min_kwh

    # Valid until this time of the day (HH:mm)
    # @return [Float]
    attr_accessor :max_kwh

    # Valid until this time of the day (HH:mm)
    # @return [Float]
    attr_accessor :min_current

    # Valid until this time of the day (HH:mm)
    # @return [Float]
    attr_accessor :max_current

    # Valid until this time of the day (HH:mm)
    # @return [Float]
    attr_accessor :min_power

    # Valid until this time of the day (HH:mm)
    # @return [Float]
    attr_accessor :max_power

    # Minimum session duration in seconds
    # @return [Integer]
    attr_accessor :min_duration

    # Maximum session duration in seconds
    # @return [Integer]
    attr_accessor :max_duration

    # Maximum session duration in seconds
    # @return [Array[DayOfWeekEnum]]
    attr_accessor :day_of_week

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['start_time'] = 'startTime'
      @_hash['end_time'] = 'endTime'
      @_hash['start_date'] = 'startDate'
      @_hash['end_date'] = 'endDate'
      @_hash['min_kwh'] = 'minKwh'
      @_hash['max_kwh'] = 'maxKwh'
      @_hash['min_current'] = 'minCurrent'
      @_hash['max_current'] = 'maxCurrent'
      @_hash['min_power'] = 'minPower'
      @_hash['max_power'] = 'maxPower'
      @_hash['min_duration'] = 'minDuration'
      @_hash['max_duration'] = 'maxDuration'
      @_hash['day_of_week'] = 'dayOfWeek'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        start_time
        end_time
        start_date
        end_date
        min_kwh
        max_kwh
        min_current
        max_current
        min_power
        max_power
        min_duration
        max_duration
        day_of_week
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(start_time = SKIP, end_time = SKIP, start_date = SKIP,
                   end_date = SKIP, min_kwh = SKIP, max_kwh = SKIP,
                   min_current = SKIP, max_current = SKIP, min_power = SKIP,
                   max_power = SKIP, min_duration = SKIP, max_duration = SKIP,
                   day_of_week = SKIP)
      @start_time = start_time unless start_time == SKIP
      @end_time = end_time unless end_time == SKIP
      @start_date = start_date unless start_date == SKIP
      @end_date = end_date unless end_date == SKIP
      @min_kwh = min_kwh unless min_kwh == SKIP
      @max_kwh = max_kwh unless max_kwh == SKIP
      @min_current = min_current unless min_current == SKIP
      @max_current = max_current unless max_current == SKIP
      @min_power = min_power unless min_power == SKIP
      @max_power = max_power unless max_power == SKIP
      @min_duration = min_duration unless min_duration == SKIP
      @max_duration = max_duration unless max_duration == SKIP
      @day_of_week = day_of_week unless day_of_week == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      start_time = hash.key?('startTime') ? hash['startTime'] : SKIP
      end_time = hash.key?('endTime') ? hash['endTime'] : SKIP
      start_date = hash.key?('startDate') ? hash['startDate'] : SKIP
      end_date = hash.key?('endDate') ? hash['endDate'] : SKIP
      min_kwh = hash.key?('minKwh') ? hash['minKwh'] : SKIP
      max_kwh = hash.key?('maxKwh') ? hash['maxKwh'] : SKIP
      min_current = hash.key?('minCurrent') ? hash['minCurrent'] : SKIP
      max_current = hash.key?('maxCurrent') ? hash['maxCurrent'] : SKIP
      min_power = hash.key?('minPower') ? hash['minPower'] : SKIP
      max_power = hash.key?('maxPower') ? hash['maxPower'] : SKIP
      min_duration = hash.key?('minDuration') ? hash['minDuration'] : SKIP
      max_duration = hash.key?('maxDuration') ? hash['maxDuration'] : SKIP
      day_of_week = hash.key?('dayOfWeek') ? hash['dayOfWeek'] : SKIP

      # Create object from extracted values.
      Restrictions.new(start_time,
                       end_time,
                       start_date,
                       end_date,
                       min_kwh,
                       max_kwh,
                       min_current,
                       max_current,
                       min_power,
                       max_power,
                       min_duration,
                       max_duration,
                       day_of_week)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} start_time: #{@start_time}, end_time: #{@end_time}, start_date:"\
      " #{@start_date}, end_date: #{@end_date}, min_kwh: #{@min_kwh}, max_kwh: #{@max_kwh},"\
      " min_current: #{@min_current}, max_current: #{@max_current}, min_power: #{@min_power},"\
      " max_power: #{@max_power}, min_duration: #{@min_duration}, max_duration: #{@max_duration},"\
      " day_of_week: #{@day_of_week}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} start_time: #{@start_time.inspect}, end_time: #{@end_time.inspect},"\
      " start_date: #{@start_date.inspect}, end_date: #{@end_date.inspect}, min_kwh:"\
      " #{@min_kwh.inspect}, max_kwh: #{@max_kwh.inspect}, min_current: #{@min_current.inspect},"\
      " max_current: #{@max_current.inspect}, min_power: #{@min_power.inspect}, max_power:"\
      " #{@max_power.inspect}, min_duration: #{@min_duration.inspect}, max_duration:"\
      " #{@max_duration.inspect}, day_of_week: #{@day_of_week.inspect}>"
    end
  end
end
