# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # SearchByIdLocationRespone Model.
  class SearchByIdLocationRespone < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique Internal identifier used to refer to this Location by Shell
    # Recharge
    # @return [String]
    attr_accessor :uid

    # Identifier as given by the Shell Recharge Operator, unique for that
    # Operator
    # @return [String]
    attr_accessor :external_id

    # Coordinates of the Shell Recharge Site Location
    # @return [Coordinates]
    attr_accessor :coordinates

    # Operator of this Shell Recharge Location
    # @return [String]
    attr_accessor :operator_name

    # Address of the Shell Recharge Location
    # @return [Address]
    attr_accessor :address

    # Accessibility of the Location
    # @return [AccessibilityV2]
    attr_accessor :accessibility

    # Accessibility of the Location
    # @return [Array[SearchByIdEvse]]
    attr_accessor :evses

    # Optional Opening Hours of the Location. Please note that it is not
    # available for all sites.
    # @return [Array[OpeningHoursObject]]
    attr_accessor :opening_hours

    # ISO8601-compliant UTC datetime of the last update of the location
    # @return [String]
    attr_accessor :updated

    # the type of the location. Could be "UNKNOWN".
    # @return [String]
    attr_accessor :location_type

    # Unique Id of the operator
    # @return [String]
    attr_accessor :operator_id

    # Whether the location is open 24/7
    # @return [TrueClass | FalseClass]
    attr_accessor :open_twenty_four_seven

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['uid'] = 'uid'
      @_hash['external_id'] = 'externalId'
      @_hash['coordinates'] = 'coordinates'
      @_hash['operator_name'] = 'operatorName'
      @_hash['address'] = 'address'
      @_hash['accessibility'] = 'accessibility'
      @_hash['evses'] = 'evses'
      @_hash['opening_hours'] = 'openingHours'
      @_hash['updated'] = 'updated'
      @_hash['location_type'] = 'locationType'
      @_hash['operator_id'] = 'operatorId'
      @_hash['open_twenty_four_seven'] = 'openTwentyFourSeven'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        uid
        external_id
        coordinates
        operator_name
        address
        accessibility
        evses
        opening_hours
        updated
        location_type
        operator_id
        open_twenty_four_seven
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(uid = SKIP, external_id = SKIP, coordinates = SKIP,
                   operator_name = SKIP, address = SKIP, accessibility = SKIP,
                   evses = SKIP, opening_hours = SKIP, updated = SKIP,
                   location_type = SKIP, operator_id = SKIP,
                   open_twenty_four_seven = SKIP)
      @uid = uid unless uid == SKIP
      @external_id = external_id unless external_id == SKIP
      @coordinates = coordinates unless coordinates == SKIP
      @operator_name = operator_name unless operator_name == SKIP
      @address = address unless address == SKIP
      @accessibility = accessibility unless accessibility == SKIP
      @evses = evses unless evses == SKIP
      @opening_hours = opening_hours unless opening_hours == SKIP
      @updated = updated unless updated == SKIP
      @location_type = location_type unless location_type == SKIP
      @operator_id = operator_id unless operator_id == SKIP
      @open_twenty_four_seven = open_twenty_four_seven unless open_twenty_four_seven == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      uid = hash.key?('uid') ? hash['uid'] : SKIP
      external_id = hash.key?('externalId') ? hash['externalId'] : SKIP
      coordinates = Coordinates.from_hash(hash['coordinates']) if hash['coordinates']
      operator_name = hash.key?('operatorName') ? hash['operatorName'] : SKIP
      address = Address.from_hash(hash['address']) if hash['address']
      accessibility = AccessibilityV2.from_hash(hash['accessibility']) if hash['accessibility']
      # Parameter is an array, so we need to iterate through it
      evses = nil
      unless hash['evses'].nil?
        evses = []
        hash['evses'].each do |structure|
          evses << (SearchByIdEvse.from_hash(structure) if structure)
        end
      end

      evses = SKIP unless hash.key?('evses')
      # Parameter is an array, so we need to iterate through it
      opening_hours = nil
      unless hash['openingHours'].nil?
        opening_hours = []
        hash['openingHours'].each do |structure|
          opening_hours << (OpeningHoursObject.from_hash(structure) if structure)
        end
      end

      opening_hours = SKIP unless hash.key?('openingHours')
      updated = hash.key?('updated') ? hash['updated'] : SKIP
      location_type = hash.key?('locationType') ? hash['locationType'] : SKIP
      operator_id = hash.key?('operatorId') ? hash['operatorId'] : SKIP
      open_twenty_four_seven =
        hash.key?('openTwentyFourSeven') ? hash['openTwentyFourSeven'] : SKIP

      # Create object from extracted values.
      SearchByIdLocationRespone.new(uid,
                                    external_id,
                                    coordinates,
                                    operator_name,
                                    address,
                                    accessibility,
                                    evses,
                                    opening_hours,
                                    updated,
                                    location_type,
                                    operator_id,
                                    open_twenty_four_seven)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} uid: #{@uid}, external_id: #{@external_id}, coordinates: #{@coordinates},"\
      " operator_name: #{@operator_name}, address: #{@address}, accessibility: #{@accessibility},"\
      " evses: #{@evses}, opening_hours: #{@opening_hours}, updated: #{@updated}, location_type:"\
      " #{@location_type}, operator_id: #{@operator_id}, open_twenty_four_seven:"\
      " #{@open_twenty_four_seven}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} uid: #{@uid.inspect}, external_id: #{@external_id.inspect}, coordinates:"\
      " #{@coordinates.inspect}, operator_name: #{@operator_name.inspect}, address:"\
      " #{@address.inspect}, accessibility: #{@accessibility.inspect}, evses: #{@evses.inspect},"\
      " opening_hours: #{@opening_hours.inspect}, updated: #{@updated.inspect}, location_type:"\
      " #{@location_type.inspect}, operator_id: #{@operator_id.inspect}, open_twenty_four_seven:"\
      " #{@open_twenty_four_seven.inspect}>"
    end
  end
end
