# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Each Location will contain one or more EVSEs (Electric Vehicle Supply
  # Equipment). Each EVSE is capable of charging one car at a time.
  class SearchByIdEvse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Internal identifier used to refer to single individual  EVSE unit.
    # @return [String]
    attr_accessor :uid

    # Identifier of the Evse as given by the Operator, unique for that Operator
    # @return [String]
    attr_accessor :external_id

    # Standard EVSEId identifier (ISO-IEC-15118)
    # @return [String]
    attr_accessor :evse_id

    # The current status of the EVSE units availability
    # @return [EvseVOStatusEnum]
    attr_accessor :status

    # ISO8601-compliant UTC datetime of the last update of the EVSE
    # @return [String]
    attr_accessor :updated

    # An optional number/string printed on the outside of the EVSE for visual
    # identification
    # @return [String]
    attr_accessor :physical_reference

    # List of all connectors available on this EVSE unit.
    # @return [Array[SearchByIdConnector]]
    attr_accessor :connectors

    # Methods that can be used to Authorize sessions on this EVSE
    # @return [Array[SingleLocationMarkerAuthorizationMethodsItemsEnum]]
    attr_accessor :authorization_methods

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['uid'] = 'uid'
      @_hash['external_id'] = 'externalId'
      @_hash['evse_id'] = 'evseId'
      @_hash['status'] = 'status'
      @_hash['updated'] = 'updated'
      @_hash['physical_reference'] = 'physicalReference'
      @_hash['connectors'] = 'connectors'
      @_hash['authorization_methods'] = 'authorizationMethods'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        uid
        external_id
        evse_id
        status
        updated
        physical_reference
        connectors
        authorization_methods
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(uid = SKIP, external_id = SKIP, evse_id = SKIP,
                   status = SKIP, updated = SKIP, physical_reference = SKIP,
                   connectors = SKIP, authorization_methods = SKIP)
      @uid = uid unless uid == SKIP
      @external_id = external_id unless external_id == SKIP
      @evse_id = evse_id unless evse_id == SKIP
      @status = status unless status == SKIP
      @updated = updated unless updated == SKIP
      @physical_reference = physical_reference unless physical_reference == SKIP
      @connectors = connectors unless connectors == SKIP
      @authorization_methods = authorization_methods unless authorization_methods == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      uid = hash.key?('uid') ? hash['uid'] : SKIP
      external_id = hash.key?('externalId') ? hash['externalId'] : SKIP
      evse_id = hash.key?('evseId') ? hash['evseId'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      updated = hash.key?('updated') ? hash['updated'] : SKIP
      physical_reference =
        hash.key?('physicalReference') ? hash['physicalReference'] : SKIP
      # Parameter is an array, so we need to iterate through it
      connectors = nil
      unless hash['connectors'].nil?
        connectors = []
        hash['connectors'].each do |structure|
          connectors << (SearchByIdConnector.from_hash(structure) if structure)
        end
      end

      connectors = SKIP unless hash.key?('connectors')
      authorization_methods =
        hash.key?('authorizationMethods') ? hash['authorizationMethods'] : SKIP

      # Create object from extracted values.
      SearchByIdEvse.new(uid,
                         external_id,
                         evse_id,
                         status,
                         updated,
                         physical_reference,
                         connectors,
                         authorization_methods)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} uid: #{@uid}, external_id: #{@external_id}, evse_id: #{@evse_id}, status:"\
      " #{@status}, updated: #{@updated}, physical_reference: #{@physical_reference}, connectors:"\
      " #{@connectors}, authorization_methods: #{@authorization_methods}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} uid: #{@uid.inspect}, external_id: #{@external_id.inspect}, evse_id:"\
      " #{@evse_id.inspect}, status: #{@status.inspect}, updated: #{@updated.inspect},"\
      " physical_reference: #{@physical_reference.inspect}, connectors: #{@connectors.inspect},"\
      " authorization_methods: #{@authorization_methods.inspect}>"
    end
  end
end
