# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # SingleLocationMarkerAuthorizationMethodsItems.
  class SingleLocationMarkerAuthorizationMethodsItemsEnum
    SINGLE_LOCATION_MARKER_AUTHORIZATION_METHODS_ITEMS_ENUM = [
      # TODO: Write general description for NEWMOTIONAPP
      NEWMOTIONAPP = 'NewMotionApp'.freeze,

      # TODO: Write general description for RFIDTOKEN
      RFIDTOKEN = 'RFIDToken'.freeze,

      # TODO: Write general description for PNC
      PNC = 'PnC'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      SINGLE_LOCATION_MARKER_AUTHORIZATION_METHODS_ITEMS_ENUM.include?(value)
    end
  end
end
