# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # A Marker is a place on the map that represent a single Location
  class SingleLocationMarkerV2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Minimum of all status values in the Marker, e.g. if at least one Evse in
    # the Marker is available, the value will be available
    # @return [SingleLocationMarkerStatusEnum]
    attr_accessor :status

    # Coordinates of the Shell Recharge Site Location
    # @return [Coordinates]
    attr_accessor :coordinates

    # Total number of Evse units in Locations that this Marker represents
    # @return [Float]
    attr_accessor :evse_count

    # Maximum power in kW across all locations grouped in this marker
    # (disregarding availability)
    # @return [Float]
    attr_accessor :max_power

    # Number of Locations that this Marker represents in the given set of bounds
    # @return [Float]
    attr_accessor :location_count

    # Unique ID of the Location this Marker represents
    # @return [String]
    attr_accessor :location_uid

    # Methods that can be used to Authorize sessions on this EVSE
    # @return [Array[SingleLocationMarkerAuthorizationMethodsItemsEnum]]
    attr_accessor :authorization_methods

    # Operator of this Shell Recharge Location
    # @return [String]
    attr_accessor :operator_name

    # Type of the Marker, in this case it will always be SingleLocation
    # @return [String]
    attr_reader :marker_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash['coordinates'] = 'coordinates'
      @_hash['evse_count'] = 'evseCount'
      @_hash['max_power'] = 'maxPower'
      @_hash['location_count'] = 'locationCount'
      @_hash['location_uid'] = 'locationUid'
      @_hash['authorization_methods'] = 'authorizationMethods'
      @_hash['operator_name'] = 'operatorName'
      @_hash['marker_type'] = 'markerType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        status
        coordinates
        evse_count
        max_power
        location_count
        location_uid
        authorization_methods
        operator_name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(status = SKIP, coordinates = SKIP, evse_count = SKIP,
                   max_power = SKIP, location_count = SKIP, location_uid = SKIP,
                   authorization_methods = SKIP, operator_name = SKIP)
      @status = status unless status == SKIP
      @coordinates = coordinates unless coordinates == SKIP
      @evse_count = evse_count unless evse_count == SKIP
      @max_power = max_power unless max_power == SKIP
      @location_count = location_count unless location_count == SKIP
      @location_uid = location_uid unless location_uid == SKIP
      @authorization_methods = authorization_methods unless authorization_methods == SKIP
      @operator_name = operator_name unless operator_name == SKIP
      @marker_type = 'SingleLocation'
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash.key?('status') ? hash['status'] : SKIP
      coordinates = Coordinates.from_hash(hash['coordinates']) if hash['coordinates']
      evse_count = hash.key?('evseCount') ? hash['evseCount'] : SKIP
      max_power = hash.key?('maxPower') ? hash['maxPower'] : SKIP
      location_count = hash.key?('locationCount') ? hash['locationCount'] : SKIP
      location_uid = hash.key?('locationUid') ? hash['locationUid'] : SKIP
      authorization_methods =
        hash.key?('authorizationMethods') ? hash['authorizationMethods'] : SKIP
      operator_name = hash.key?('operatorName') ? hash['operatorName'] : SKIP

      # Create object from extracted values.
      SingleLocationMarkerV2.new(status,
                                 coordinates,
                                 evse_count,
                                 max_power,
                                 location_count,
                                 location_uid,
                                 authorization_methods,
                                 operator_name)
    end

    # Validates an instance of the object from a given value.
    # @param [SingleLocationMarkerV2 | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.marker_type,
                                     ->(val) { val.instance_of? String })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['markerType'],
                            ->(val) { val.instance_of? String })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} status: #{@status}, coordinates: #{@coordinates}, evse_count:"\
      " #{@evse_count}, max_power: #{@max_power}, location_count: #{@location_count},"\
      " location_uid: #{@location_uid}, authorization_methods: #{@authorization_methods},"\
      " operator_name: #{@operator_name}, marker_type: #{@marker_type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} status: #{@status.inspect}, coordinates: #{@coordinates.inspect},"\
      " evse_count: #{@evse_count.inspect}, max_power: #{@max_power.inspect}, location_count:"\
      " #{@location_count.inspect}, location_uid: #{@location_uid.inspect}, authorization_methods:"\
      " #{@authorization_methods.inspect}, operator_name: #{@operator_name.inspect}, marker_type:"\
      " #{@marker_type.inspect}>"
    end
  end
end
