# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # StopChargeSessionRequestBodyJson Model.
  class StopChargeSessionRequestBodyJson < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Session Id is to be fetched
    # @return [String]
    attr_accessor :sesssion_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sesssion_id'] = 'SesssionId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(sesssion_id = nil)
      @sesssion_id = sesssion_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sesssion_id = hash.key?('SesssionId') ? hash['SesssionId'] : nil

      # Create object from extracted values.
      StopChargeSessionRequestBodyJson.new(sesssion_id)
    end
  end
end
