# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module ShellEv
  # Tariff metadata aligned with TariffV2 GraphQL schema
  class TariffV2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique identifier for the tariff
    # @return [String]
    attr_accessor :tariff_id

    # Tariff type classification
    # @return [TariffTypeEnum]
    attr_accessor :tariff_type

    # Tariff type classification
    # @return [PowerRange]
    attr_accessor :power_range

    # Internal identifier used by the platform
    # @return [String]
    attr_accessor :internal_id

    # Unique identifier of the operator
    # @return [String]
    attr_accessor :operator_id

    # Unique identifier of the provider
    # @return [String]
    attr_accessor :provider_id

    # ISO 4217 Currency Code
    # @return [String]
    attr_accessor :currency

    # ISO 4217 Currency Code
    # @return [Array[TariffAltText]]
    attr_accessor :tariff_alt_text

    # ISO 4217 Currency Code
    # @return [Float]
    attr_accessor :min_price

    # ISO 4217 Currency Code
    # @return [Float]
    attr_accessor :max_price

    # ISO 4217 Currency Code
    # @return [Array[TariffElement]]
    attr_accessor :elements

    # ISO 4217 Currency Code
    # @return [DateTime]
    attr_accessor :start_date_time

    # ISO 4217 Currency Code
    # @return [DateTime]
    attr_accessor :end_date_time

    # ISO 4217 Currency Code
    # @return [DateTime]
    attr_accessor :last_updated

    # Identifier of the actor who created the tariff
    # @return [String]
    attr_accessor :created_by

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['tariff_id'] = 'tariffId'
      @_hash['tariff_type'] = 'tariffType'
      @_hash['power_range'] = 'powerRange'
      @_hash['internal_id'] = 'internalId'
      @_hash['operator_id'] = 'operatorId'
      @_hash['provider_id'] = 'providerId'
      @_hash['currency'] = 'currency'
      @_hash['tariff_alt_text'] = 'tariffAltText'
      @_hash['min_price'] = 'minPrice'
      @_hash['max_price'] = 'maxPrice'
      @_hash['elements'] = 'elements'
      @_hash['start_date_time'] = 'startDateTime'
      @_hash['end_date_time'] = 'endDateTime'
      @_hash['last_updated'] = 'lastUpdated'
      @_hash['created_by'] = 'createdBy'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      %w[
        tariff_alt_text
      ]
    end

    def initialize(tariff_id = nil, tariff_type = nil, power_range = nil,
                   internal_id = nil, operator_id = nil, provider_id = nil,
                   currency = nil, tariff_alt_text = nil, min_price = nil,
                   max_price = nil, elements = nil, start_date_time = nil,
                   end_date_time = nil, last_updated = nil, created_by = nil)
      @tariff_id = tariff_id
      @tariff_type = tariff_type
      @power_range = power_range
      @internal_id = internal_id
      @operator_id = operator_id
      @provider_id = provider_id
      @currency = currency
      @tariff_alt_text = tariff_alt_text
      @min_price = min_price
      @max_price = max_price
      @elements = elements
      @start_date_time = start_date_time
      @end_date_time = end_date_time
      @last_updated = last_updated
      @created_by = created_by
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      tariff_id = hash.key?('tariffId') ? hash['tariffId'] : nil
      tariff_type = hash.key?('tariffType') ? hash['tariffType'] : nil
      power_range = PowerRange.from_hash(hash['powerRange']) if hash['powerRange']
      internal_id = hash.key?('internalId') ? hash['internalId'] : nil
      operator_id = hash.key?('operatorId') ? hash['operatorId'] : nil
      provider_id = hash.key?('providerId') ? hash['providerId'] : nil
      currency = hash.key?('currency') ? hash['currency'] : nil
      # Parameter is an array, so we need to iterate through it
      tariff_alt_text = nil
      unless hash['tariffAltText'].nil?
        tariff_alt_text = []
        hash['tariffAltText'].each do |structure|
          tariff_alt_text << (TariffAltText.from_hash(structure) if structure)
        end
      end

      tariff_alt_text = nil unless hash.key?('tariffAltText')
      min_price = hash.key?('minPrice') ? hash['minPrice'] : nil
      max_price = hash.key?('maxPrice') ? hash['maxPrice'] : nil
      # Parameter is an array, so we need to iterate through it
      elements = nil
      unless hash['elements'].nil?
        elements = []
        hash['elements'].each do |structure|
          elements << (TariffElement.from_hash(structure) if structure)
        end
      end

      elements = nil unless hash.key?('elements')
      start_date_time = if hash.key?('startDateTime')
                          (DateTimeHelper.from_rfc3339(hash['startDateTime']) if hash['startDateTime'])
                        end
      end_date_time = if hash.key?('endDateTime')
                        (DateTimeHelper.from_rfc3339(hash['endDateTime']) if hash['endDateTime'])
                      end
      last_updated = if hash.key?('lastUpdated')
                       (DateTimeHelper.from_rfc3339(hash['lastUpdated']) if hash['lastUpdated'])
                     end
      created_by = hash.key?('createdBy') ? hash['createdBy'] : nil

      # Create object from extracted values.
      TariffV2.new(tariff_id,
                   tariff_type,
                   power_range,
                   internal_id,
                   operator_id,
                   provider_id,
                   currency,
                   tariff_alt_text,
                   min_price,
                   max_price,
                   elements,
                   start_date_time,
                   end_date_time,
                   last_updated,
                   created_by)
    end

    def to_custom_start_date_time
      DateTimeHelper.to_rfc3339(start_date_time)
    end

    def to_custom_end_date_time
      DateTimeHelper.to_rfc3339(end_date_time)
    end

    def to_custom_last_updated
      DateTimeHelper.to_rfc3339(last_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} tariff_id: #{@tariff_id}, tariff_type: #{@tariff_type}, power_range:"\
      " #{@power_range}, internal_id: #{@internal_id}, operator_id: #{@operator_id}, provider_id:"\
      " #{@provider_id}, currency: #{@currency}, tariff_alt_text: #{@tariff_alt_text}, min_price:"\
      " #{@min_price}, max_price: #{@max_price}, elements: #{@elements}, start_date_time:"\
      " #{@start_date_time}, end_date_time: #{@end_date_time}, last_updated: #{@last_updated},"\
      " created_by: #{@created_by}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} tariff_id: #{@tariff_id.inspect}, tariff_type: #{@tariff_type.inspect},"\
      " power_range: #{@power_range.inspect}, internal_id: #{@internal_id.inspect}, operator_id:"\
      " #{@operator_id.inspect}, provider_id: #{@provider_id.inspect}, currency:"\
      " #{@currency.inspect}, tariff_alt_text: #{@tariff_alt_text.inspect}, min_price:"\
      " #{@min_price.inspect}, max_price: #{@max_price.inspect}, elements: #{@elements.inspect},"\
      " start_date_time: #{@start_date_time.inspect}, end_date_time: #{@end_date_time.inspect},"\
      " last_updated: #{@last_updated.inspect}, created_by: #{@created_by.inspect}>"
    end
  end
end
