# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # TariffElement Model.
  class TariffElement < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[PriceComponent]]
    attr_accessor :price_components

    # TODO: Write general description for this method
    # @return [Restrictions]
    attr_accessor :restrictions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['price_components'] = 'priceComponents'
      @_hash['restrictions'] = 'restrictions'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        restrictions
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(price_components = nil, restrictions = SKIP)
      @price_components = price_components
      @restrictions = restrictions unless restrictions == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      price_components = nil
      unless hash['priceComponents'].nil?
        price_components = []
        hash['priceComponents'].each do |structure|
          price_components << (PriceComponent.from_hash(structure) if structure)
        end
      end

      price_components = nil unless hash.key?('priceComponents')
      restrictions = Restrictions.from_hash(hash['restrictions']) if hash['restrictions']

      # Create object from extracted values.
      TariffElement.new(price_components,
                        restrictions)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} price_components: #{@price_components}, restrictions: #{@restrictions}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} price_components: #{@price_components.inspect}, restrictions:"\
      " #{@restrictions.inspect}>"
    end
  end
end
