# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Tariff type classification
  class TariffTypeEnum
    TARIFF_TYPE_ENUM = [
      # TODO: Write general description for DRIVER
      DRIVER = 'DRIVER'.freeze,

      # TODO: Write general description for ROAMING
      ROAMING = 'ROAMING'.freeze,

      # TODO: Write general description for REIMBURSEMENT
      REIMBURSEMENT = 'REIMBURSEMENT'.freeze,

      # TODO: Write general description for VMSP
      VMSP = 'VMSP'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TARIFF_TYPE_ENUM.include?(value)
    end

    def self.from_value(value, default_value = DRIVER)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'driver' then DRIVER
      when 'roaming' then ROAMING
      when 'reimbursement' then REIMBURSEMENT
      when 'vmsp' then VMSP
      else
        default_value
      end
    end
  end
end
