# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # TariffAltText Model.
  class TariffAltText < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # ISO language code
    # @return [String]
    attr_accessor :language

    # Human readable tariff description
    # @return [String]
    attr_accessor :text

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['language'] = 'language'
      @_hash['text'] = 'text'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(language = nil, text = nil)
      @language = language
      @text = text
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      language = hash.key?('language') ? hash['language'] : nil
      text = hash.key?('text') ? hash['text'] : nil

      # Create object from extracted values.
      TariffAltText.new(language,
                        text)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} language: #{@language}, text: #{@text}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} language: #{@language.inspect}, text: #{@text.inspect}>"
    end
  end
end
