# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Type of the price component
  class TypeEnum
    TYPE_ENUM = [
      # TODO: Write general description for TIME
      TIME = 'TIME'.freeze,

      # TODO: Write general description for ENERGY
      ENERGY = 'ENERGY'.freeze,

      # TODO: Write general description for FLAT
      FLAT = 'FLAT'.freeze,

      # TODO: Write general description for PARKING_TIME
      PARKING_TIME = 'PARKING_TIME'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE_ENUM.include?(value)
    end

    def self.from_value(value, default_value = TIME)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'time' then TIME
      when 'energy' then ENERGY
      when 'flat' then FLAT
      when 'parking_time' then PARKING_TIME
      else
        default_value
      end
    end
  end
end
