# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'

require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'

require_relative 'shell_ev/api_helper'
require_relative 'shell_ev/client'

# Utilities
require_relative 'shell_ev/utilities/file_wrapper'
require_relative 'shell_ev/utilities/date_time_helper'
require_relative 'shell_ev/utilities/union_type_lookup'

# Http
require_relative 'shell_ev/http/http_call_back'
require_relative 'shell_ev/http/http_method_enum'
require_relative 'shell_ev/http/http_request'
require_relative 'shell_ev/http/http_response'

# Logger
require_relative 'shell_ev/http/auth/o_auth2'

# Models
require_relative 'shell_ev/models/base_model'
require_relative 'shell_ev/models/response'
require_relative 'shell_ev/models/location_respone_object'
require_relative 'shell_ev/models/coordinates'
require_relative 'shell_ev/models/address'
require_relative 'shell_ev/models/accessibility'
require_relative 'shell_ev/models/evse_vo'
require_relative 'shell_ev/models/connector_vo'
require_relative 'shell_ev/models/electrical_properties'
require_relative 'shell_ev/models/tariff_vo'
require_relative 'shell_ev/models/opening_hours_object'
require_relative 'shell_ev/models/bad_request_err_msg'
require_relative 'shell_ev/models/unauthorized_err_msg'
require_relative 'shell_ev/models/not_found_err_msg'
require_relative 'shell_ev/models/ratelimit_err_msg'
require_relative 'shell_ev/models/internal_error_object'
require_relative 'shell_ev/models/serviceunavailable_err_msg'
require_relative 'shell_ev/models/single_location_marker_response'
require_relative 'shell_ev/models/single_location_marker'
require_relative 'shell_ev/models/multi_location_marker'
require_relative 'shell_ev/models/chargesession_start_body'
require_relative 'shell_ev/models/inline_response202'
require_relative 'shell_ev/models/inline_response202_data'
require_relative 'shell_ev/models/inline_response2021'
require_relative 'shell_ev/models/data_retrieve'
require_relative 'shell_ev/models/charge_retrieve_state'
require_relative 'shell_ev/models/charge_error'
require_relative 'shell_ev/models/data_active'
require_relative 'shell_ev/models/get_charge_session_retrieve_response200_json'
require_relative 'shell_ev/models/active_response200_json'
require_relative 'shell_ev/models/tariff'
require_relative 'shell_ev/models/o_auth_token'
require_relative 'shell_ev/models/' \
                 'single_location_marker_authorization_methods_items_enum'
require_relative 'shell_ev/models/get_ev_locations_evse_status_enum'
require_relative 'shell_ev/models/get_ev_locations_connector_types_enum'
require_relative 'shell_ev/models/get_ev_locations_authorization_methods_enum'
require_relative 'shell_ev/models/nearby_locations_evse_status_enum'
require_relative 'shell_ev/models/nearby_locations_connector_types_enum'
require_relative 'shell_ev/models/nearby_locations_authorization_methods_enum'
require_relative 'shell_ev/models/locations_markers_evse_status_enum'
require_relative 'shell_ev/models/locations_markers_connector_types_enum'
require_relative 'shell_ev/models/locations_markers_authorization_methods_enum'
require_relative 'shell_ev/models/' \
                 'get_charge_session_retrieve_response200_json_status_enum'
require_relative 'shell_ev/models/active_response200_json_status_enum'
require_relative 'shell_ev/models/accessibility_status_enum'
require_relative 'shell_ev/models/evse_vo_status_enum'
require_relative 'shell_ev/models/evse_vo_authorization_methods_enum'
require_relative 'shell_ev/models/connector_vo_connector_type_enum'
require_relative 'shell_ev/models/connector_vo_updated_by_enum'
require_relative 'shell_ev/models/electrical_properties_power_type_enum'
require_relative 'shell_ev/models/tariff_vo_updated_by_enum'
require_relative 'shell_ev/models/opening_hours_object_week_day_enum'
require_relative 'shell_ev/models/single_location_marker_status_enum'
require_relative 'shell_ev/models/inline_response202_status_enum'
require_relative 'shell_ev/models/inline_response2021_status_enum'
require_relative 'shell_ev/models/o_auth_provider_error_enum'

# Exceptions
require_relative 'shell_ev/exceptions/api_exception'
require_relative 'shell_ev/exceptions/bad_request_exception'
require_relative 'shell_ev/exceptions/unauthorized_exception'
require_relative 'shell_ev/exceptions/not_found_exception'
require_relative 'shell_ev/exceptions/too_many_requests_exception'
require_relative 'shell_ev/exceptions/internal_server_error_exception'
require_relative 'shell_ev/exceptions/serviceunavailable_exception'
require_relative 'shell_ev/exceptions/o_auth_provider_exception'

require_relative 'shell_ev/configuration'

# Controllers
require_relative 'shell_ev/controllers/base_controller'
require_relative 'shell_ev/controllers/locations_controller'
require_relative 'shell_ev/controllers/charging_controller'
require_relative 'shell_ev/controllers/o_auth_authorization_controller'
