# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
