# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # HTTP 401 Error Response class.
  class HTTP401ErrorResponseException < APIException
    SKIP = Object.new
    private_constant :SKIP

    # A unique request id in GUID format. The value is written to the Shell API
    # Platform audit log for end to end traceability of a request.
    # @return [String]
    attr_accessor :request_id

    # Indicates overall status of the request
    # @return [ResponseBaseStatusEnum]
    attr_accessor :status

    # Details of error(s) encountered
    # @return [Array[ResponseError401AllOf1ErrorsItems]]
    attr_accessor :errors

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpResponse] The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @request_id = hash.key?('RequestId') ? hash['RequestId'] : nil
      @status = hash.key?('Status') ? hash['Status'] : nil
      # Parameter is an array, so we need to iterate through it
      @errors = nil
      unless hash['Errors'].nil?
        @errors = []
        hash['Errors'].each do |structure|
          @errors << (ResponseError401AllOf1ErrorsItems.from_hash(structure) if structure)
        end
      end

      @errors = nil unless hash.key?('Errors')
    end
  end
end
