# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Serviceunavailable class.
  class ServiceunavailableException < APIException
    SKIP = Object.new
    private_constant :SKIP

    # requestId is unique identifier value that is attached to requests and
    # messages that allow reference to a particular transaction or event chain.
    # @return [String]
    attr_accessor :request_id

    # Status of the request
    # @return [String]
    attr_accessor :status

    # Exception details of the error
    # @return [Array[ServiceunavailableErrMsg]]
    attr_accessor :errors

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpResponse] The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @request_id = hash.key?('requestId') ? hash['requestId'] : SKIP
      @status = hash.key?('status') ? hash['status'] : SKIP
      # Parameter is an array, so we need to iterate through it
      @errors = nil
      unless hash['errors'].nil?
        @errors = []
        hash['errors'].each do |structure|
          @errors << (ServiceunavailableErrMsg.from_hash(structure) if structure)
        end
      end

      @errors = SKIP unless hash.key?('errors')
    end
  end
end
