# shell_ev
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module ShellEv
  # An enum for SDK environments.
  class Environment
    # PRODUCTION: Production Server
    # ENVIRONMENT2: Production Server
    # ENVIRONMENT3: Test Server
    # ENVIRONMENT4: Test Server
    ENVIRONMENT = [
      PRODUCTION = 'production'.freeze,
      ENVIRONMENT2 = 'environment2'.freeze,
      ENVIRONMENT3 = 'environment3'.freeze,
      ENVIRONMENT4 = 'environment4'.freeze
    ].freeze

    # Converts a string or symbol into a valid Environment constant.
    def self.from_value(value, default_value = PRODUCTION)
      return default_value if value.nil?

      str = value.to_s.strip.downcase
      case str
      when 'production' then PRODUCTION
      when 'environment2' then ENVIRONMENT2
      when 'environment3' then ENVIRONMENT3
      when 'environment4' then ENVIRONMENT4

      else
        warn "[Environment] Unknown environment '#{value}', falling back to #{default_value} "
        default_value
      end
    end
  end

  # An enum for API servers.
  class Server
    SERVER = [
      DEFAULT = 'default'.freeze
    ].freeze

    # Converts a string or symbol into a valid Server constant.
    def self.from_value(value, default_value = DEFAULT)
      return default_value if value.nil?

      default_value
    end
  end

  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration < CoreLibrary::HttpClientConfiguration
    def o_auth_client_id
      @client_credentials_auth_credentials.o_auth_client_id
    end

    def o_auth_client_secret
      @client_credentials_auth_credentials.o_auth_client_secret
    end

    def o_auth_token
      @client_credentials_auth_credentials.o_auth_token
    end

    # The attribute readers for properties.
    attr_reader :environment, :client_credentials_auth_credentials

    class << self
      attr_reader :environments
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 60,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put], http_callback: nil, proxy_settings: nil,
      environment: Environment::PRODUCTION, o_auth_client_id: nil,
      o_auth_client_secret: nil, o_auth_token: nil,
      client_credentials_auth_credentials: nil
    )
      super connection: connection, adapter: adapter, timeout: timeout,
            max_retries: max_retries, retry_interval: retry_interval,
            backoff_factor: backoff_factor, retry_statuses: retry_statuses,
            retry_methods: retry_methods, http_callback: http_callback,
            proxy_settings: proxy_settings

      # Current API environment
      @environment = String(environment)

      # OAuth 2 Client ID
      @o_auth_client_id = o_auth_client_id

      # OAuth 2 Client Secret
      @o_auth_client_secret = o_auth_client_secret

      # Object for storing information about the OAuth token
      @o_auth_token = if o_auth_token.is_a? OAuthToken
                        OAuthToken.from_hash o_auth_token.to_hash
                      else
                        o_auth_token
                      end

      # Initializing OAuth 2 Client Credentials Grant credentials with the provided auth parameters
      @client_credentials_auth_credentials = create_auth_credentials_object(
        o_auth_client_id, o_auth_client_secret, o_auth_token,
        client_credentials_auth_credentials
      )

      # The Http Client to use for making requests.
      set_http_client CoreLibrary::FaradayClient.new(self)
    end

    def clone_with(connection: nil, adapter: nil, timeout: nil,
                   max_retries: nil, retry_interval: nil, backoff_factor: nil,
                   retry_statuses: nil, retry_methods: nil, http_callback: nil,
                   proxy_settings: nil, environment: nil, o_auth_client_id: nil,
                   o_auth_client_secret: nil, o_auth_token: nil,
                   client_credentials_auth_credentials: nil)
      connection ||= self.connection
      adapter ||= self.adapter
      timeout ||= self.timeout
      max_retries ||= self.max_retries
      retry_interval ||= self.retry_interval
      backoff_factor ||= self.backoff_factor
      retry_statuses ||= self.retry_statuses
      retry_methods ||= self.retry_methods
      http_callback ||= self.http_callback
      proxy_settings ||= self.proxy_settings
      environment ||= self.environment
      client_credentials_auth_credentials = create_auth_credentials_object(
        o_auth_client_id, o_auth_client_secret, o_auth_token,
        client_credentials_auth_credentials || self.client_credentials_auth_credentials
      )

      Configuration.new(
        connection: connection, adapter: adapter, timeout: timeout,
        max_retries: max_retries, retry_interval: retry_interval,
        backoff_factor: backoff_factor, retry_statuses: retry_statuses,
        retry_methods: retry_methods, http_callback: http_callback,
        proxy_settings: proxy_settings, environment: environment,
        client_credentials_auth_credentials: client_credentials_auth_credentials
      )
    end

    def create_auth_credentials_object(o_auth_client_id, o_auth_client_secret,
                                       o_auth_token,
                                       client_credentials_auth_credentials)
      return client_credentials_auth_credentials if o_auth_client_id.nil? &&
                                                    o_auth_client_secret.nil? &&
                                                    o_auth_token.nil?

      warn('The \'o_auth_client_id\', \'o_auth_client_secret\', \'o_auth_token'\
           '\' params are deprecated. Use \'client_credentials_auth_credential'\
           's\' param instead.')

      unless client_credentials_auth_credentials.nil?
        return client_credentials_auth_credentials.clone_with(
          o_auth_client_id: o_auth_client_id,
          o_auth_client_secret: o_auth_client_secret,
          o_auth_token: o_auth_token
        )
      end

      ClientCredentialsAuthCredentials.new(
        o_auth_client_id: o_auth_client_id,
        o_auth_client_secret: o_auth_client_secret, o_auth_token: o_auth_token
      )
    end

    # All the environments the SDK can run in.
    ENVIRONMENTS = {
      Environment::PRODUCTION => {
        Server::DEFAULT => 'https://api.shell.com/ev'
      },
      Environment::ENVIRONMENT2 => {
        Server::DEFAULT => 'https://api.shell.com/v2/oauth'
      },
      Environment::ENVIRONMENT3 => {
        Server::DEFAULT => 'https://api-test.shell.com/ev'
      },
      Environment::ENVIRONMENT4 => {
        Server::DEFAULT => 'https://api-test.shell.com/v2/oauth'
      }
    }.freeze

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] server The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def get_base_uri(server = Server::DEFAULT)
      ENVIRONMENTS[environment][server].clone
    end

    # Builds a Configuration instance using environment variables.
    def self.build_default_config_from_env
      # === Core environment ===
      environment = Environment.from_value(ENV.fetch('ENVIRONMENT', 'production'))
      timeout = (ENV['TIMEOUT'] || 60).to_f
      max_retries = (ENV['MAX_RETRIES'] || 0).to_i
      retry_interval = (ENV['RETRY_INTERVAL'] || 1).to_f
      backoff_factor = (ENV['BACKOFF_FACTOR'] || 2).to_f
      retry_statuses = ENV.fetch('RETRY_STATUSES',
                                 '[408, 413, 429, 500, 502, 503, 504, 521, 522, 524]').gsub(/[\[\]]/, '')
                                          .split(',')
                                          .map(&:strip)
                                          .map do |item|
                                            item.match?(/\A\d+\z/) ? item.to_i : item.downcase
                                          end
      retry_methods = ENV.fetch('RETRY_METHODS', '%i[get put]').gsub(/[\[\]]/, '')
                                          .split(',')
                                          .map(&:strip)
                                          .map do |item|
                                            item.match?(/\A\d+\z/) ? item.to_i : item.downcase
                                          end

      # === Authentication credentials ===
      client_credentials_auth_credentials = ClientCredentialsAuthCredentials.from_env

      # === Proxy settings ===
      proxy_settings = ProxySettings.from_env

      Configuration.new(
        environment: environment,
        timeout: timeout,
        max_retries: max_retries,
        retry_interval: retry_interval,
        backoff_factor: backoff_factor,
        retry_statuses: retry_statuses,
        retry_methods: retry_methods,
        client_credentials_auth_credentials: client_credentials_auth_credentials,
        proxy_settings: proxy_settings
      )
    end
  end
end
